apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://charts.bitwarden.com/'
    targetRevision: "*"
    chart: self-host
    helm:
      values: |
        persistence:
          data:
            enabled: true
            size: 10Gi
          log:
            enabled: true
            size: 5Gi
          backup:
            enabled: true
            size: 5Gi

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bitwarden

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
