apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-self-host-mssqldata
  namespace: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-self-host-mssqllog
  namespace: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-self-host-mssqlbackups
  namespace: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-identity-cert
  namespace: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-self-host-dataprotection
  namespace: bitwarden
spec:   
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-self-host-licenses
  namespace: bitwarden
spec:   
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-self-host-dataprotection
  namespace: bitwarden
spec:   
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-self-host-attachments
  namespace: bitwarden
spec:   
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
